### ISSUE TITLE
Request for the csv file of Diabetes

### ISSUE THREAD

**Issue by DeepakKumarKhatri** [priya6971/Statistics-Session-Notes#1]
I have just completed your lecture on **types of statistics** and now I want to try the code part by myself for that I need a _**CSV file on diabetes**_ that you worked on in the lecture.

It would be great if you include that one in **[Statistics-Session-Notes](https://github.com/priya6971/Statistics-Session-Notes)/Code Files/**

**Comment by priya6971** [comment]
It's done Deepak, please check under Dataset Folder under the same repository.
